### ISSUE TITLE
[Request] Add a license to the project

### ISSUE THREAD

**Issue by kriNon** [hippowombat/AdvancedLights#1]
Hey,
I'd love to make use of this in my game. Would you consider adding a license to this repo?

Currently without a license 
https://choosealicense.com/no-permission/

Maybe consider going with an MIT License if you want something simple and unrestrictive:
https://choosealicense.com/licenses/mit/

Thanks!

**Comment by hippowombat** [comment]
Hey there, thanks for calling this out! I've assigned the MIT license to this repository in [this commit.](https://github.com/hippowombat/AdvancedLights/commit/35ebd960d8387389fd732f792c7b16e1815b7b3c)

Cheers!
